author:
  name: Quinton Harris
  email: quinton.harris@gmail.com
  github: dznqbit
  linkedin: dznqbit
title: dznqbit
logo: /assets/img/giacometti.png
favicon: true
remote_theme: jekyll/minima
google_analytics: UA-108144808-1
plugins:
  #- jekyll-sitemap
  #- jekyll-seo-tag
  #- jemoji
  - jekyll-remote-theme

cdn:
  jsdelivr:
    enabled: true

minima:
  skin: auto